version: "3"

services:
  storefront:
    container_name: storefront
    build:
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SALEOR_API_URL: ${NEXT_PUBLIC_SALEOR_API_URL}
        NEXT_PUBLIC_STOREFRONT_URL: ${NEXT_PUBLIC_STOREFRONT_URL}
    restart: unless-stopped
    ports:
      - 8030:3000
    environment:
      NEXT_PUBLIC_SALEOR_API_URL: ${NEXT_PUBLIC_SALEOR_API_URL}
      NEXT_PUBLIC_STOREFRONT_URL: ${NEXT_PUBLIC_STOREFRONT_URL}
    networks:
      - strongpack-network
    env_file:
      - ./.env
  # Add more containers below (nginx, postgres, etc.)

networks:
  strongpack-network:
    name: strongpack-network
  #  external: false
